### ISSUE TITLE
/var/lib/gems/2.3.0/gems/ffi-1.0.11/lib/ffi/library.rb:150:in "ffi_libraries": no library specified (LoadError)

### ISSUE THREAD

**Issue by a4popa** [copiousfreetime/tyrantmanager#12]
Hello I have a problem when I want to start using tyrantmanager.

> $ tyrantmanager setup /tmp/tyrant

`/var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/lib/tyrant_manager/paths.rb:78:in <class:TyrantManager> : uninitialized constant TyrantManager::Config (NameError)
Did you mean?  RbConfig
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/lib/tyrant_manager/paths.rb:7:in <top (required)>
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/lib/tyrant_manager.rb:9:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/bin/tyrantmanager:9:in "<top (required)>"
        from /usr/local/bin/tyrantmanager:23:in "load"
        from /usr/local/bin/tyrantmanager:23:in "<main>"`

then I edit line 78: 
Config with RbConfig

try again:
$ tyrantmanager setup /tmp/tyrant
` /var/lib/gems/2.3.0/gems/ffi-1.0.11/lib/ffi/library.rb:150:in "ffi_libraries": no library specified (LoadError)
        from /var/lib/gems/2.3.0/gems/ffi-1.0.11/lib/ffi/library.rb:228:in "attach_function"
        from /var/lib/gems/2.3.0/gems/rufus-tokyo-1.0.7/lib/rufus/tokyo/cabinet/lib.rb:63:in "<module:CabinetLib>"
        from /var/lib/gems/2.3.0/gems/rufus-tokyo-1.0.7/lib/rufus/tokyo/cabinet/lib.rb:31:in "<module:Tokyo>"
        from /var/lib/gems/2.3.0/gems/rufus-tokyo-1.0.7/lib/rufus/tokyo/cabinet/lib.rb:26:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/rufus-tokyo-1.0.7/lib/rufus/tokyo.rb:57:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/rufus-tokyo-1.0.7/lib/rufus/tokyo/tyrant.rb:26:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/lib/tyrant_manager/tyrant_instance.rb:7:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/lib/tyrant_manager.rb:263:in "<top (required)>"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in "require"
        from /var/lib/gems/2.3.0/gems/tyrantmanager-1.7.7/bin/tyrantmanager:9:in "<top (required)>"
        from /usr/local/bin/tyrantmanager:23:in "load"
        from /usr/local/bin/tyrantmanager:23:in "<main>"`
Note:
- Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x86_64)
- tokyotyrant-1.1.33
- tokyocabinet-1.4.32

**Comment by copiousfreetime** [comment]
@a4popa My apologies for taking so long to get back to you on this. tyrant-manager is mostly a archived project, I don't use it at all anymore. My guess is that you also need to install the tokyotyrant-devel and tokyocabinet-devel packages on ubuntu. Feel free to fork and or send pull requests if you want.
